#!/bin/bash

# source variables
confDir="${confDir:-$HOME/.config}"
kittyConf="${confDir}/kitty/kitty.conf"
hydeKitty="${HYDE_DATA_HOME}/kitty.conf"

INC_LINE="include hyde.conf"

# Check if kitty.conf exists and is a symlink
if [ -L "$kittyConf" ]; then
    echo "Warning: $kittyConf is a symlink, preserving it and not modifying"
    exit 0
fi

# Check if kitty.conf exists, if not create a minimal one
if [ ! -f "$kittyConf" ]; then
    echo "# Kitty configuration" > "$kittyConf"
    echo "# Generated by HyDE" >> "$kittyConf"
    echo "" >> "$kittyConf"
fi

# Remove old include patterns and add the new one at the top
sed -i "/include .*hyde\.conf/d" "$kittyConf"
sed -i "/include .*share\/hyde\/kitty\.conf.*/d" "$kittyConf"

# Ensure the include line is at the top and remove duplicates
if ! grep -Fxq "$INC_LINE" "$kittyConf"; then
    sed -i "1i $INC_LINE" "$kittyConf"
fi

# Refresh kitty terminal
killall -SIGUSR1 kitty
