# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = ,qwerty
    follow_mouse = 1
    sensitivity = 1.0
    force_no_accel = 0
    accel_profile = flat
    # numlock_by_default = true
    special_fallthrough = 1
    emulate_discrete_scroll = 0

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
        scroll_factor = 0.7
        drag_3fg = 3
    }
}

binds {
    workspace_back_and_forth = 1
    hide_special_on_workspace_change = 1
}


# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, vertical, dispatcher, togglespecialworkspace
# gesture = 2, pinchin, fullscreen
# gesture = 2, pinchout, nofullscreen
# gesture = 2, pinchin, dispatcher, exec, sh -c "notify-send 'Pinch in'; hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 * 1.1}')"
# gesture = 2, pinchout, dispatcher, exec, sh -c "notify-send 'Pinch out'; hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 * 0.9}')"

# for window swallow similar to devour
misc {
    enable_swallow = true
    swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
    exit_window_retains_fullscreen = true
    new_window_takes_over_fullscreen = 1
}

cursor {
    hide_on_key_press = true
}

# Don't show update on first launch
ecosystem {
    no_update_news = true
}

exec-once = hyprpm reload -n

general {
    layout = scrolling
}

plugin {
    hyprscrolling {
        focus_fit_method = 1
        fullscreen_on_one_column = true
    }
}
